---
title: "lab10-donggyun-kim"
author: "Donggyun Kim"
date: "11/23/2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error = TRUE)
```

```{r}
head(USArrests)
states <- rownames(USArrests)

nchar(states)
tolower(states)
toupper(states)
casefold(states, upper = TRUE)
casefold(states, upper = FALSE)

num_char <- nchar(states)
freq_char <- table(num_char)
barplot(freq_char, las = 1)
```

```{r}
paste(head(states, 5), head(num_char, 5), sep = " = ")
paste(head(states, 5), collapse = '')

substr(states, start = nchar(states) - 2, stop = nchar(states))
paste0(substr(states, start = 1, stop = 1), substr(states, start = nchar(states) - 2, stop = nchar(states)))

```

### Challenge
```{r}
states_list <- list(0)

for (i in min(num_char) : max(num_char)) {
  if (i %% 2 == 0) {
    states_list[[i - min(num_char) + 1]] <- toupper(paste(states[num_char == i], collapse = ", "))
  } else {
    states_list[[i - min(num_char) + 1]] <- tolower(paste(states[num_char == i], collapse = ", "))
  }
}

names(states_list) <- paste0(min(num_char) : max(num_char), "-chars")

states_list

```


### Converting from Fahrenheit Degrees
```{r}
to_celsius <- function(x = 1) {
  (x - 32) * (5 / 9)
}

to_kelvin <- function(x = 1) {
  (x + 459.67) * (5 / 9)
}

to_reaumur <- function(x = 1) {
  (x - 32) * (4 / 9)
}

to_rankine <- function(x = 1) {
  x + 459.67
}

temp_convert <- function(x = 1, to = "celsius") {
  switch(tolower(to),
         "celsius" = to_celsius(x),
         "kelvin" = to_kelvin(x),
         "reaumur" = to_reaumur(x),
         "rankine" = to_rankine(x))
}

temp_convert(30, "celsius")
temp_convert(30, "Celsius")
temp_convert(30, "CELSIUS")
```

### Names of files

```{r}
# first way
file <- rep("file", 10)
num <- 1:10
csv <- rep(".csv")
paste(file, num, csv, sep = "")

# second way
paste("file", 1:10, ".csv", sep = "")

# third way
paste0("file", 1:10, ".csv")

# rename
rename <- paste0("file", 1:10, ".csv")
sub(pattern = "file", replacement = "dataset", rename)
```

### Using function `cat()`
```{r}
outfile <- "output.txt"

cat("---\n", file = outfile)
cat("title: \"lab10\"\n", file = outfile, append = TRUE)
cat("author: \"Donggyun Kim\"\n", file = outfile, append = TRUE)
cat("date: \"2017-11-23\"\n", file = outfile, append = TRUE)
cat("output: github_document\n", file = outfile, append = TRUE)
cat("---\n", file = outfile, append = TRUE)

cat("\nThis is the first line\n", file = outfile, append = TRUE)
cat("A 2nd line\n", file = "output.txt", append = TRUE)

cat("\nThe quick brown fox jumps over the lazy dog\n",
    file = outfile, append = TRUE)
```

### Valid Color Names

```{r}
is_color <- function(x) {
  if (sum(colors() == x) > 0) {
    TRUE
  } else {
    FALSE
  }
}

is_color("yellow")  

is_color("blu")     

is_color("turkuoise")

```

```{r}
colplot <- function(col) {
  if (is_color(col)) {
    plot(runif(10), runif(10), main = paste("Testing color", col, sep = " "))
  } else {
    stop(paste("invalid color", col, sep = " "))
  }
}

colplot('tomato')

colplot('tomate')
```

### Counting number of vowels

```{r}
set.seed(1)
letrs <- sample(letters, size = 100, replace = TRUE)
head(letrs)

count_vowel <- function(x) {
  a <- sum(x == "a")
  e <- sum(x == "e")
  i <- sum(x == "i")
  o <- sum(x == "o")
  u <- sum(x == "u")
  
  cat(paste0("a: ", a))
  cat(paste0("\ne: ", e))
  cat(paste0("\ni: ", i))
  cat(paste0("\no: ", o))
  cat(paste0("\nu: ", u))
}

count_vowel(letrs)
```

```{r}
count_consonant <- function(letrs) {
  b <- sum(letrs == "b")
  c <- sum(letrs == "c")
  d <- sum(letrs == "d")
  f <- sum(letrs == "f")
  g <- sum(letrs == "g")
  h <- sum(letrs == "h")
  j <- sum(letrs == "j")
  k <- sum(letrs == "k")
  l <- sum(letrs == "l")
  m <- sum(letrs == "m")
  n <- sum(letrs == "n")
  p <- sum(letrs == "p")
  q <- sum(letrs == "q")
  r <- sum(letrs == "r")
  s <- sum(letrs == "s")
  t <- sum(letrs == "t")
  v <- sum(letrs == "v")
  w <- sum(letrs == "w")
  x <- sum(letrs == "x")
  y <- sum(letrs == "y")
  z <- sum(letrs == "z")
  
  vec <- c(b = b, c = c, d = d, f = f, g = g, h = h, j = j, k = k, l = l, m = m, 
           n = n, p = p, q = q, r = r, s = s, t = t, v = v, w = w, x = x, y = y,
           z = z)
  vec
}

count_consonant(letrs)
```

### Number of letters, vowels, and consonants

```{r}
count_letters <- function(letrs) {
  cat(paste0("\"letters: ", length(letrs), "\"\n"))
  cat(paste0("\"vowels: ", length(letrs) - sum(count_consonant(letrs)), "\"\n"))
  cat(paste0("\"consonants: ", sum(count_consonant(letrs)), "\""))
}

count_letters(letrs)
```



