---
title: "HW03 - Ranking NBA Teams"
author: "Donggyun Kim"
date: "2017-10-07"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, message=FALSE}
setwd("~/Desktop/STAT 133/stat133-hws-fall17/hw03/")
library(readr)
library(dplyr)
library(ggplot2)
teams<- read_csv("./data/nba2017_teams.csv")
attributes(teams)$row.names <- teams$team
```

# Basic Rankings
```{r}
ggplot(teams, aes(x = reorder(team, salary), y = salary)) +
  geom_bar(stat='identity') +
  coord_flip() +
  geom_hline(yintercept = mean(teams$salary), col = "Red") +
  labs(x = "Team", y = "Salary (in millions)", title = "NBA Teams ranked by Total Salary")
```

```{r}
ggplot(teams, aes(x = reorder(team, points), y = points)) +
  geom_bar(stat='identity') +
  coord_flip() +
  geom_hline(yintercept = mean(teams$points), col = "Red") +
  labs(x = "Team", y = "Total Points", title = "NBA Teams ranked by Total Points")
```

```{r}
ggplot(teams, aes(x = reorder(team, efficiency), y = efficiency)) +
  geom_bar(stat='identity') +
  coord_flip() +
  geom_hline(yintercept = mean(teams$efficiency), col = "Red") +
  labs(x = "Team", y = "Total Efficiency", title = "NBA Teams ranked by Total Efficiency")
```

# Principal Components Analysis (PCA)
```{r}
teams1 <- teams %>%
  select(points3, points2, free_throws, off_rebounds, def_rebounds, assists, steals,
         blocks, turnovers, fouls)

pca <- prcomp(teams1, scale. = TRUE)

eigs <- data.frame(
  eigenvalue = round(pca$sdev^2, 4),
  prop = round(pca$sdev^2 / sum(pca$sdev^2), 4)
)
eigs$cumprop <- cumsum(eigs$prop)
eigs
```

```{r}
pci <- data.frame(pca$x)
ggplot(pci, aes(x = PC1, y = PC2)) + geom_text(label = rownames(pci))
```

```{r}
z1 <- pci %>%
  select(PC1)
s1 <- (z1 - min(z1))/(max(z1) - min(z1))*100
s1$team <- attributes(s1)$row.names
ggplot(s1, aes(x = reorder(team, PC1), y = PC1)) +
  geom_bar(stat = "identity") +
  coord_flip() +
  geom_hline(yintercept = mean(s1$PC1), col = "red") +
  labs(x = "Team", y = "Firtst PC (scaled from 0 to 100)", title = "NBA Teams ranked by scaled PC1")
```